---
- name: Build a 4-Node Kubernetes cluster with containerd runtime cri.
  hosts: kubecluster
  become: true
  gather_facts: true
  vars:
   v_reboot: false
   pod_net_cidr: 10.10.0.0/16 #default
   service_net_cidr: 10.20.0.0/16 #default
   service_dns_domain: k8s.sanderson.com #default

  roles:
    - kubecluster

