---
- name: Configure automation user to be able to access kubectl
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/automation/.kube/config
    remote_src: true

- name: Add to bashrc file
  ansible.builtin.lineinfile:
    path: /home/automation/.bashrc
    line: export KUBECONFIG=/home/automation/.kube/config


- name: Apply bashrc changes
  ansible.builtin.shell: source /home/automation/.bashrc



