---
- name: Remove previous server and pool entries.
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    line: ^pool.*
    state: absent

- name: Set NTP time source to google's NTP server
  notify: BounceNTP
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    line: 'server  time.google.com  iburst maxpoll 16'

