---
- name: Set Kernel Modules at Boot Time
  ansible.builtin.copy:
    dest: /etc/modules-load.d/kubernetes.conf
    content: |
              br_netfilter
              ip_vs
              ip_vs_rr
              ip_vs_wrr
              ip_vs_sh
              overlay

- name: Set SysCtl Parameters at Boot Time (IPv4 Routing)
  notify: sysctl_handler
  ansible.builtin.copy:
    dest: /etc/sysctl.d/kubernetes.conf
    content: |
              net.ipv4.ip_forward = 1
              net.bridge.bridge-nf-call-ip6tables = 1
              net.bridge.bridge-nf-call-iptables = 1

- name: Flush Handlers to apply Ip routing rules now.
  ansible.builtin.meta: flush_handlers
