---
- name: BUILD K8S | Download GO interpreter
  when: " inventory_hostname in groups['master'] "
  ansible.builtin.uri:
    url: https://go.dev/dl/go1.24.3.linux-amd64.tar.gz
    dest: /home/automation/
    owner: automation
    group: automation
    mode: 0644

- name: BUILD K8S | Extract GO interpereter
  when: " inventory_hostname in groups['master'] "
  ansible.builtin.unarchive:
    src: /home/automation/go1.24.3.linux-amd64.tar.gz
    dest: /usr/local/
    owner: automation
    group: automation
    mode: 0755
    remote_src: true

- name: BUILD K8S | Download latest HELM source code from GITHUB
  when: " inventory_hostname in groups['master'] "
  ansible.builtin.shell: cd /usr/local/ && git clone https://github.com/helm/helm.git && chown -Rf automation:automation helm

- name: BUILD K8S | Build helm from source
  when: " inventory_hostname in groups['master'] "
  ansible.builtin.shell: export PATH=$PATH:/usr/local/go/bin/ && cd /usr/local/helm/ && make && make install && chown -R automation:automation     /usr/local/helm
  register: build_helm

- name: DEBUG | Build Helm Output
  when: " inventory_hostname in groups['master'] "
  ansible.builtin.debug:
    var: build_helm
