---
- name: HELM | Install Nginx Ingress Controller
  become: false
  when: 
    - " inventory_hostname in groups['master'] "
    - v_configurehelm is true 
  ansible.builtin.shell: helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace 
  register: ingress_installer

- name: DEBUG | Results of Ingress Controller Install
  become: false
  when: 
    - " inventory_hostname in groups['master'] "
    - v_configurehelm is true 
  ansible.builtin.debug:
    var: ingress_installer


