---
- name: Start Kubelet service
  loop:
    - kubelet
    - containerd
  ansible.builtin.service:
    name: "{{item}}"
    state: restarted
    enabled: true

- name: Configure containerd
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml

- name: Enable Systemd Cgroups for containerd
  ansible.builtin.replace:
     path: /etc/containerd/config.toml
     regexp: ^\s*SystemdCgroup.*false.*$
     replace: '            SystemdCgroup = true'

- name: Restart containerd
  ansible.builtin.service:
     name: containerd
     state: restarted

- name: Docker Pull Kube Master images to Control Plane node
  when: " 'control' in inventory_hostname"
  ansible.builtin.shell: kubeadm config images pull
  register: kubeadm_controlplaneinit

- name: View Results
  when: " 'control' in inventory_hostname"
  ansible.builtin.debug:
    var: kubeadm_controlplaneinit

- name: Kubeadm Initialize POD network
  when: " 'control' in inventory_hostname"
  ansible.builtin.shell: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kubeadm_podnetinit

- name: View Results of Initialization of Master
  when: " 'control' in inventory_hostname"
  ansible.builtin.debug:
    var: kubeadm_podnetinit

