---
- name: Install Packages
  loop:
    - kubernetes-cni
    - containerd.io
    - kubelet
    - kubeadm
    - kubectl
  ansible.builtin.dnf:
     name: "{{item}}"
     state: present
     disable_excludes: true
