---
- name: Join command
  when: " inventory_hostname in groups['workers'] "
  ansible.builtin.shell: kubeadm join {{control_plane_fqdn}}:6443 --discovery-token-unsafe-skip-ca-verification  --token {{hostvars['control']['join_token']}} 2>&1|tee /var/log/kube-join.log
  register: cmd

- name: Print output of join
  ansible.builtin.debug:
     var: cmd.stdout

- name: Set worker node to type "worker"
  ansible.builtin.shell: kubectl label node {{inventory_hostname}}  node-role.kubernetes.io/worker=worker
  register: set_worker_type

- name: DEBUG | Changing nodes to worker type
  ansible.builtin.debug:
    var: set_worker_type


